security:
    encoders:
        UsuarioBundle\Entity\user: {algorithm: sha512, iterations: 10}

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN
        ROLE_USER_WEB: ROLE_USER_WEB

    providers:
        user:
            entity: {class: usuarioBundle\Entity\user, property: email}
        

    firewalls:
        administracion:
            pattern: ^/
            provider: user
            anonymous: ~ 
            form_login:
                login_path: login
                check_path: login_check
                use_referer: true
                always_use_default_target_path: true
                default_target_path: backend_homepage
            logout:
                path: logout
    access_control:

        - { path: ^/administracion/*, roles: [ROLE_SUPER_ADMIN,ROLE_USER] }
        - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY}