<?php

namespace usuarioBundle\Repository;

/**
 * superadministradorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class superadministradorRepository extends \Doctrine\ORM\EntityRepository
{
}
