<?php

namespace usuarioBundle\Repository;

/**
 * userwebRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userwebRepository extends \Doctrine\ORM\EntityRepository
{
}
