<?php

namespace usuarioBundle\Repository;

/**
 * userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUseremail($email, $iduser) {
        $em = $this->getEntityManager();
        $where = " WHERE usuario.email = '" . $email ."' ";
        if ($iduser > 0){
            $where .= " AND usuario.id <> " . $iduser;
        }
        $sql = " SELECT usuario FROM usuarioBundle:user usuario ".$where ;
        $consulta = $em->createQuery($sql)->getResult();
        return $consulta; 
    }
}
