<?php

namespace coreBundle\Repository;

/**
 * peliculaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class peliculaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllQuery() {
        $inner = "";

        $em = $this->getEntityManager();
        $where = " WHERE 1=1 ";
        $order = " ORDER BY pelicula.votaciontotal DESC";
        $sql = " SELECT pelicula FROM coreBundle:pelicula pelicula ".$where.$order;
        $consulta = $em->createQuery($sql);
        return $consulta; 
    }
    
    public function findAllFavoritasQuery($idusuario) {
        $inner = "";
        $where = " WHERE 1=1 ";
        if($idusuario){
           $inner .= " JOIN pelicula.pelicula_favorita favorita ";
           $where .= " AND favorita.id = ".$idusuario;
        }
        
        $em = $this->getEntityManager();
        $order = " ORDER BY pelicula.votaciontotal ASC";
        $sql = " SELECT pelicula FROM coreBundle:pelicula pelicula ".$inner.$where.$order;
        $consulta = $em->createQuery($sql);
        return $consulta; 
    }
}
