<?php

namespace coreBundle\Repository;

/**
 * votacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class votacionRepository extends \Doctrine\ORM\EntityRepository
{
}
